baseURL = "https://tushar994.github.io/"
languageCode = "en-us"
title = "My New Portfolio"
theme = ["github.com/mirus-ua/hugo-theme-re-terminal"]



[params]
  # Choose a color: orange, blue, red, green, pink, paper
  themeColor = "orange"
  contentTypeName = "posts"
  fullWidthTheme = false
  centerTheme = true
  [params.Logo]
    logoText = "About Me"

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles"
  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
  [[menu.main]]
    identifier = "opensource"
    name = "Open Source"
    url = "/opensource"